### ISSUE TITLE
我这个少文件

### ISSUE THREAD

**Issue by laizhiVP** [Maru-zhang/MRVLCPlayer#10]
提示MobileVLCKit/MobileVLCKit.h没有找到？这个什么原因啊

**Comment by sushushu** [comment]
我也是这个原因

**Comment by Maru-zhang** [comment]
文章里面有写，是因为这个repo没有包括VLC的二进制包，需要自行下载，因为这个二进制包太大了。

**Comment by sushushu** [comment]
去官网下载就好了,已经成功跑起来
